name: Build 

on: ['push', 'workflow_dispatch']

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Get Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ibrahimardic
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ibrahimardic/airline-manager:latest .

      - name: Docker Push Image
        run: |
          docker push ibrahimardic/airline-manager:latest