name: Airline CRUD Operations

on:
  push:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Get code
      uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Apply Migrations
      run: python manage.py migrate

    - name: Install Newman
      run: npm install -g newman

    - name: Run server in Background
      run: |
        python manage.py runserver 127.0.0.1:8000 & 
  
    - name: Wait for server to start
      run: sleep 10
    
    - name: Run Postman Tests
      run: |
        newman run tests/Airline_Crud_Operations.json --delay-request 1000 
    # --delay-request to avoid overloading the server
    
    - name: Stop Server After Tests
      run: |
        fuser -k 8000/tcp